apiVersion: v1
kind: Namespace
metadata:
  name: ebug-core
  labels:
    app.kubernetes.io/part-of: ebug-tracking
---
apiVersion: v1
kind: Namespace
metadata:
  name: ebug-ingestion
  labels:
    app.kubernetes.io/part-of: ebug-tracking
---
apiVersion: v1
kind: Namespace
metadata:
  name: ebug-ai
  labels:
    app.kubernetes.io/part-of: ebug-tracking
---
apiVersion: v1
kind: Namespace
metadata:
  name: ebug-data
  labels:
    app.kubernetes.io/part-of: ebug-tracking
